export const BoardsActionTypes = {
    ADD_EVENT: 'ADD_EVENT',
    ADD_COLUMN: 'ADD_COLUMN',
    ADD_ROW: 'ADD_ROW',
    ADD_BOARD: 'ADD_BOARD',
    EDIT_CELL: 'EDIT_CELL',
    EDIT_COLUMN: 'EDIT_COLUMN',
    SET_CURRENT_DATE: 'SET_CURRENT_DATE',
    SET_TITLES: 'ADD_TITLES',
    SET_BOARD: 'SET_BOARD'
}